### PR TITLE
move config file to a folder

### PR DESCRIPTION
**Pull request by benasse**
It's simple to "dokerize" the app.

### CODE REVIEW

**Comment by benasse** [comment]
the README should be updated to, but I don't know how to be clear with location and configuration of the file.

**Comment by EpocDotFr** [comment]
Thank you for your pull request, however can you explain how moving the configuration file to a different folder would improve the _dokerization_ of this app?

In addition, I created the `storage` folder for files that are subject to I/O operations only, so I prefer not to move the configuration file in it.

PS: I never used Docker

**Comment by benasse** [comment]
In fact with docker, you can only map folder to the host filesystem.
It's simple if the config file is on a different folder than the code.

**Comment by benasse** [comment]
If you want to try : 
- here a docker file : https://gist.github.com/benasse/496f6fb65ae4ebf750f2d5fbff64fdf0
- to run the container `docker run -v /srv/webtodotxt/config/:/webtodotxt/storage/config/ -v /srv/webtodotxt/todo_txt/:/storage/data/ -p 8080:8080 --rm -ti webtodotxt`

**Comment by EpocDotFr** [comment]
Why do I see on your PR diff the things I commited on my master?

**Comment by EpocDotFr** [comment]
What if you map the whole root directory instead of creating a `config` directory that contains a `config.py` file?

**Comment by benasse** [comment]
Sorry , I forgot that I had used the branch master ...

If the root directory is mapped to the host fs, even if the container is updated, the original *code* will be used.

A solution could be to pass the configuration file as an argument.

**Comment by EpocDotFr** [comment]
Okay so I'm good with your MR, but can you update the readme as well?

**Comment by EpocDotFr** [comment]
Closing this PR as it's pending for one year now.

**Pull request closed without merging**
